name: Benchmark

on:
  push:
    branches: [main]
    paths:
      - 'scripts/**'
      - 'src/**'
      - 'Cargo.*'
      - 'pyproject.toml'
  pull_request:
    paths:
      - 'scripts/**'
      - 'src/**'
      - 'Cargo.*'
      - 'pyproject.toml'

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install maturin
        pip install numpy pandas plotly jinja2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build rust_annie
      run: maturin develop

    - name: Run benchmark
      run: python scripts/benchmark.py --N 5000 --D 32 --k 5 --repeats 10 --save

    - name: Generate dashboard + badge
      run: python dashboard.py

    - name: Commit and push dashboard updates
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add benchmarks/*.json docs/index.html docs/dashboard-badge.svg
        git commit -m "chore: update benchmark dashboard [skip ci]" || echo "No changes to commit"
        git push